# To build powernukkit, insert "gp build" and to initialize server use "gp init".
# To go to GitPod, go to https://gitpod.io/#https://github.com/PowerNukkit/PowerNukkit/

tasks:
  - init: bash mvnw clean install
ports:
  - port: 19132
